<?php

declare(strict_types=1);

namespace TypedDuck\ConsultRector\Reference;

/**
 * Renders the shipped reference documents from a set of {@see RuleDescriptor}s
 * (CONTEXT.md): the small `rectors-by-category.md` lookup table and the large
 * `rectors-compendium.md` accessed section-by-section via `consult-rector doc`.
 */
final class ReferenceGenerator
{
    private const GENERATED_NOTICE = '> Auto-generated by `tools/generate-references.php` — do not edit by hand.';

    /**
     * @param list<RuleDescriptor> $descriptors
     */
    public function byCategory(array $descriptors): string
    {
        /** @var array<string, list<string>> $byCategory */
        $byCategory = [];
        foreach ($descriptors as $descriptor) {
            $byCategory[$descriptor->category][] = $descriptor->fqcn;
        }
        ksort($byCategory);

        $lines = ['# Rectors by Category', '', self::GENERATED_NOTICE, ''];
        foreach ($byCategory as $category => $fqcns) {
            sort($fqcns);
            $lines[] = '## ' . $category;
            $lines[] = '';
            foreach ($fqcns as $fqcn) {
                $lines[] = '- `' . $fqcn . '`';
            }
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    /**
     * @param list<RuleDescriptor> $descriptors
     */
    public function compendium(array $descriptors): string
    {
        usort($descriptors, static fn (RuleDescriptor $a, RuleDescriptor $b): int => $a->fqcn <=> $b->fqcn);

        $lines = [
            '# Rectors Compendium',
            '',
            self::GENERATED_NOTICE,
            '> Large file — access section by section via `consult-rector doc index` / `doc section`.',
            '',
        ];
        foreach ($descriptors as $descriptor) {
            $lines[] = '## ' . $descriptor->fqcn;
            $lines[] = '';
            $lines[] = '- Category: ' . $descriptor->category;
            if ($descriptor->description !== null && $descriptor->description !== '') {
                $lines[] = '- ' . $descriptor->description;
            }
            $lines[] = '';

            $sample = $descriptor->codeSamples[0] ?? null;
            if ($sample !== null) {
                $lines[] = '```php';
                $lines[] = '// before';
                $lines[] = rtrim($sample['before']);
                $lines[] = '// after';
                $lines[] = rtrim($sample['after']);
                $lines[] = '```';
                $lines[] = '';
            }
        }

        return implode("\n", $lines);
    }
}
